spring:
  application:
    name: backend
  redis:
    host: localhost
    port: 6379 # 기본 포트
    password: # 생략 가능


# --------------------------

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1
    password: 1q2w3e
